services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: mern-frontend:dev
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://localhost:5050
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
    image: mern-backend:dev
    ports:
      - "5050:5050"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "start"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 